//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AftersalesPm_HwIssueReportShare
    {
        public long Id { get; set; }
        public Nullable<long> MainId { get; set; }
        public string ReportDetails { get; set; }
        public string InstructionService { get; set; }
        public string InstructionProduction { get; set; }
        public string FuturePlanForNxtPro { get; set; }
        public string ForwardReason { get; set; }
        public string Status { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
