//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cm_TotalPoLcAndTt
    {
        public long Id { get; set; }
        public string AllType { get; set; }
        public Nullable<long> ProjectLcId { get; set; }
        public Nullable<long> ProjectPurchaseOrderFormId { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public string OracleLcNo { get; set; }
        public string ProductType { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public Nullable<System.DateTime> LcPassDate { get; set; }
        public string LcValue { get; set; }
        public Nullable<System.DateTime> TtDate { get; set; }
        public string TtNumber { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public Nullable<System.DateTime> PoDate { get; set; }
        public string PoCategory { get; set; }
        public Nullable<int> MonNum { get; set; }
        public Nullable<long> Year { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
