//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectForecastingMaterialQtyLog
    {
        public long Id { get; set; }
        public Nullable<long> MainId { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> FG_MD_HOLD_Qty { get; set; }
        public Nullable<decimal> TotalOnhandQty { get; set; }
        public Nullable<decimal> ProductionableQty { get; set; }
        public Nullable<decimal> RepairPendingQty { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> LogAdded { get; set; }
        public Nullable<System.DateTime> LogAddedDate { get; set; }
    }
}
