//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectForecastingInfoLog
    {
        public long Id { get; set; }
        public Nullable<long> ForecastId { get; set; }
        public long ProjectMasterId { get; set; }
        public string ProjectName { get; set; }
        public string ProjectType { get; set; }
        public Nullable<System.DateTime> LaunchDate { get; set; }
        public string Plc { get; set; }
        public string Brand { get; set; }
        public string FSegment { get; set; }
        public Nullable<decimal> Display { get; set; }
        public string Battery { get; set; }
        public string Ram { get; set; }
        public string Rom { get; set; }
        public Nullable<decimal> Fob { get; set; }
        public Nullable<long> January { get; set; }
        public Nullable<long> February { get; set; }
        public Nullable<long> March { get; set; }
        public Nullable<long> April { get; set; }
        public Nullable<long> May { get; set; }
        public Nullable<long> June { get; set; }
        public Nullable<long> July { get; set; }
        public Nullable<long> August { get; set; }
        public Nullable<long> September { get; set; }
        public Nullable<long> October { get; set; }
        public Nullable<long> November { get; set; }
        public Nullable<long> December { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> LogAdded { get; set; }
        public Nullable<System.DateTime> LogAddedDate { get; set; }
    }
}
